#include<iostream>
#include<ctime>
using namespace std;

char get_userchoice();
char get_computerchoice();
void show_choice(char choice);
void check_winner(char userchoice ,char computerchoice);

int main()
{
    char player;
    char computer;

    player=get_computerchoice()
    return 0;
}

char get_userchoice(){
   
   return 0;
}
char get_computerchoice(){
  return 0;
}
void show_choice(char choice){

}
void check_winner(char userchoice ,char computerchoice){

}